uploads = []
outputs = []

[[generated]]
id = "1-BZFYpri8CcLpYO4umCK"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "eventis app icon"

[[generated]]
id = "If1bxeq1Z3TNBnuTJzgDu"
uri = "file://artifacts/mobile/assets/images/banner-concert.png"
type = "image"
title = "concert banner"

[[generated]]
id = "V8sdhx8KSdFpkukcbMEcx"
uri = "file://artifacts/mobile/assets/images/banner-tech.png"
type = "image"
title = "tech conference banner"

[[generated]]
id = "QtmYawkGCwOSp_zsfjJ-C"
uri = "file://artifacts/mobile/assets/images/banner-food.png"
type = "image"
title = "food festival banner"
